==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5d0e010 is 48 bytes inside a block of size 352 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x4F66CDF: (within /lib/i686/cmov/libc-2.7.so)
==9324==    by 0x4F6951B: fopen64 (in /lib/i686/cmov/libc-2.7.so)
==9324==    by 0x431691E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317DC9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5d0e010 is 48 bytes inside a block of size 352 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x4F66CDF: (within /lib/i686/cmov/libc-2.7.so)
==9324==    by 0x4F6951B: fopen64 (in /lib/i686/cmov/libc-2.7.so)
==9324==    by 0x431691E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317DC9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5d0c010 is 72 bytes inside a block of size 496 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5d11010 is 424 bytes inside a block of size 692 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x429E5EF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FFB5A: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426C907: PyGrammar_AddAccelerators (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D40F: PyParser_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DAB9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426C907: PyGrammar_AddAccelerators (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D40F: PyParser_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DAB9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426C907: PyGrammar_AddAccelerators (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D40F: PyParser_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DAB9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5d56010 is 48 bytes inside a block of size 672 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426C907: PyGrammar_AddAccelerators (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D40F: PyParser_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DAB9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431FA40: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5da8010 is 5,216 bytes inside a block of size 6,016 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x426D33F: PyParser_Delete (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DE5F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297438: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4328193: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43281A8: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABB08: PyDict_DelItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABB8E: PyDict_DelItemString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4326FB5: PySys_SetObject (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FB7FD: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5dac010 is 5,528 bytes inside a block of size 6,016 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x426D33F: PyParser_Delete (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DE5F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F8E2B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5dca010 is 32 bytes inside a block of size 288 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431B4D6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE63: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C613: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C7DA: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314CDF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428419B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428419B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428419B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5cfa010 is 184 bytes inside a block of size 692 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431B4D6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE7C: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C613: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C789: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314CDF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428410B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5cfa010 is 184 bytes inside a block of size 692 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431B4D6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE7C: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C613: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C789: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314CDF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D24F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D2F4: PyNode_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F7B5: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5de6010 is 4,608 bytes inside a block of size 6,016 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x426D33F: PyParser_Delete (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DE5F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42974DA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301D38: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5de2010 is 6,568 bytes inside a block of size 8,192 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42AED5C: PyMem_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4291A16: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4291B29: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FB537: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABE0E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42798D1: PyObject_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297DCC: PyFrame_FastToLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9E9B: PyEval_GetLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300D18: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABE0E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42798D1: PyObject_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297DCC: PyFrame_FastToLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9E9B: PyEval_GetLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300D18: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1D39: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426CEE7: PyNode_AddChild (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D5B4: PyParser_AddToken (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DB85: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B1D44: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426CEE7: PyNode_AddChild (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426D5B4: PyParser_AddToken (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DB85: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1D39: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302A51: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4303E30: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307E3B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BBB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BF6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4309947: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CDC2: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B1D44: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302A51: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4303E30: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307E3B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BBB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BF6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4309947: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CDC2: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1D39: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BBEC4: _PyString_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4304C8E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B1D44: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BBEC4: _PyString_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4304C8E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43050E1: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43050E1: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302506: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCFD: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302506: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCFD: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431FA40: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5df9010 is 192 bytes inside a block of size 245 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42AED5C: PyMem_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43058E0: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABE0E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42798D1: PyObject_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297DCC: PyFrame_FastToLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9E9B: PyEval_GetLocals (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300D18: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5df3010 is 208 bytes inside a block of size 848 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42AED5C: PyMem_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43058EE: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCEF: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1D30: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302A51: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4303E30: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307E3B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4306B9D: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BBB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4307BF6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4309947: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CDC2: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5dfe010 is 160 bytes inside a block of size 184 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431DC6E: PyArena_AddPyObject (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F11AE: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EF71D: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EF51B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EFA0A: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EFDB6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F3554: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F43A7: PyAST_FromNode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F7AB: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4302506: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x430CCFD: PyAST_Compile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9F0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5dfe010 is 160 bytes inside a block of size 184 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431DC6E: PyArena_AddPyObject (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F11AE: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EF71D: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EF51B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EFA0A: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42EFDB6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F3554: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F43A7: PyAST_FromNode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F7AB: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
Running test_file.test_function : output {Hello World!
} (Type,Value) = 5, Hello World!
Running py_function.multiply : output {The result of 12345 x 6789 : 83810205
} (Type,Value) = 1, 83810205
Running test_file.test_function : output {Hello World!
} (Type,Value) = 5, Hello World!
Running py_function.multiply : output {The result of 12345 x 6789 : 83810205
} (Type,Value) = 1, 83810205
Running inline source [print 'Hello World!'] : output {Hello World!
} No result returned!
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x805281D: iblocks::SafePythonObject::~SafePythonObject() (SafePythonObject.cc:20)
==9324==    by 0x804C0F9: (anonymous namespace)::Object::~Object() (PythonPlugin.cc:59)
==9324==    by 0x804BD24: test_inline_source(iblocks::PythonPlugin*) (auto_ptr.h:173)
==9324==    by 0x804BF1B: main (PythonPluginTest.cc:24)
==9324==  Address 0x5e86010 is 4,256 bytes inside a block of size 6,016 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x426D33F: PyParser_Delete (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DE5F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F8CA: Py_CompileStringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C289: iblocks::PythonPlugin::ParsePythonSource(std::string const&) (PythonPlugin.cc:233)
==9324==    by 0x804BC28: test_inline_source(iblocks::PythonPlugin*) (PythonPluginTest.cc:86)
==9324==    by 0x804BF1B: main (PythonPluginTest.cc:24)
Running inline source [print 'Hello World!'] : output {Hello World!
} No result returned!
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x5eac010 is 184 bytes inside a block of size 352 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42A0562: PyList_Append (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431B4D6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C613: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C7DA: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314CDF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1D39: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D718: _PyObject_GC_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297B93: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43009D6: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B1D44: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D718: _PyObject_GC_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297B93: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43009D6: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428410B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431855B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x628c010 is 104 bytes inside a block of size 484 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428419B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431855B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1D30: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BBEC4: _PyString_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FA2B0: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FFC51: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x6316010 is 320 bytes inside a block of size 430 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FCB11: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FCB11: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x6316010 is 320 bytes inside a block of size 430 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FCB11: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1D30: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D718: _PyObject_GC_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297B93: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43009D6: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x631a010 is 8 bytes inside a block of size 16 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x429FBB4: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300285: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C32BB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42841B3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314C07: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADB78: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FE761: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4318504: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431886A: PyImport_ImportModuleLevel (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F95D3: (within /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x6beb010 is 7,400 bytes inside a block of size 8,208 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x431DD9C: PyArena_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431FA24: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317EFA: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431FA40: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431FA40: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1D30: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BBEC4: _PyString_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BDFC5: PyString_Format (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42BE725: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4275020: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4277E03: PyNumber_Remainder (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FCA2C: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4317C58: (within /usr/lib/libpython2.5.so.1.0)
==9324==  Address 0x63d7010 is 152 bytes inside a block of size 400 free'd
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42B1DE3: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D718: _PyObject_GC_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297B93: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43009D6: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
Running numpy_test.myrange : output {PyArray_ISBOOL: 0
PyArray_ISINTEGER: 0
PyArray_ISFLOAT: 1
PyArray_ISSTRING: 0
PyArray_ISCOMPLEX: 0
PyArray_ISPYTHON: 1
PyArray_NDIM(pObj) = 2
dims = 0x5f90ef0
dims[0] = 5
PyArray_DIM(pObj, 0) = 5
PyArray_STRIDE(pObj, 0) = 16
dims[1] = 2
PyArray_DIM(pObj, 1) = 2
PyArray_STRIDE(pObj, 1) = 8
pObj->ob_type->tp_name = numpy.ndarray
} No result returned!
Running numpy_test.myrange : output {PyArray_ISBOOL: 0
PyArray_ISINTEGER: 0
PyArray_ISFLOAT: 1
PyArray_ISSTRING: 0
PyArray_ISCOMPLEX: 0
PyArray_ISPYTHON: 1
PyArray_NDIM(pObj) = 2
dims = 0x63ea008
dims[0] = 5
PyArray_DIM(pObj, 0) = 5
PyArray_STRIDE(pObj, 0) = 16
dims[1] = 2
PyArray_DIM(pObj, 1) = 2
PyArray_STRIDE(pObj, 1) = 8
pObj->ob_type->tp_name = numpy.ndarray
} No result returned!
Running test_file.test_function : output {Hello World!
} (Type,Value) = 5, Hello World!
Running py_function.multiply : output {The result of 12345 x 6789 : 83810205
} (Type,Value) = 1, 83810205
Running test_file.test_function : output {Hello World!
} (Type,Value) = 5, Hello World!
Running py_function.multiply : output {The result of 12345 x 6789 : 83810205
} (Type,Value) = 1, 83810205
Running inline source [print 'Hello World!'] : output {Hello World!
} No result returned!
Running inline source [print 'Hello World!'] : output {Hello World!
} No result returned!
Running numpy_test.myrange : output {PyArray_ISBOOL: 0
PyArray_ISINTEGER: 0
PyArray_ISFLOAT: 1
PyArray_ISSTRING: 0
PyArray_ISCOMPLEX: 0
PyArray_ISPYTHON: 1
PyArray_NDIM(pObj) = 2
dims = 0x6461050
dims[0] = 5
PyArray_DIM(pObj, 0) = 5
PyArray_STRIDE(pObj, 0) = 16
dims[1] = 2
PyArray_DIM(pObj, 1) = 2
PyArray_STRIDE(pObj, 1) = 8
pObj->ob_type->tp_name = numpy.ndarray
} No result returned!
Running numpy_test.myrange : output {PyArray_ISBOOL: 0
PyArray_ISINTEGER: 0
PyArray_ISFLOAT: 1
PyArray_ISSTRING: 0
PyArray_ISCOMPLEX: 0
PyArray_ISPYTHON: 1
PyArray_NDIM(pObj) = 2
dims = 0x648fba0
dims[0] = 5
PyArray_DIM(pObj, 0) = 5
PyArray_STRIDE(pObj, 0) = 16
dims[1] = 2
PyArray_DIM(pObj, 1) = 2
PyArray_STRIDE(pObj, 1) = 8
pObj->ob_type->tp_name = numpy.ndarray
} No result returned!
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5e64010 is 8 bytes before a block of size 332 alloc'd
==9324==    at 0x4023D6E: malloc (vg_replace_malloc.c:207)
==9324==    by 0x42B1A9F: PyObject_Malloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432E9FF: _PyObject_GC_Malloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432EB07: _PyObject_GC_NewVar (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297BD1: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301877: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42985E9: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274A16: PyObject_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42F9C7B: PyEval_CallObjectWithKeywords (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4274BFB: PyObject_CallObject (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804CA3D: iblocks::PythonPlugin::RunPythonCode(std::string const&, std::string const&, std::string const&) (PythonPlugin.cc:181)
==9324==    by 0x804B2EB: test_function_call(iblocks::PythonPlugin*) (PythonPluginTest.cc:39)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5e20010 is not stack'd, malloc'd or (recently) free'd
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5e99010 is 2,800 bytes inside a block of size 6,016 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x426D33F: PyParser_Delete (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426DE5F: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F78B: PyParser_ASTFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431F9D0: PyRun_StringFlags (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42FF495: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DACB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5e45010 is 8 bytes before a block of size 362 alloc'd
==9324==    at 0x4023D6E: malloc (vg_replace_malloc.c:207)
==9324==    by 0x42B1A9F: PyObject_Malloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B98E7: PyString_FromStringAndSize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BB54: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BCFC: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431BE4E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C613: PyMarshal_ReadObjectFromString (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431C789: PyMarshal_ReadLastObjectFromFile (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DACB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5e45010 is 8 bytes before a block of size 362 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DACB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D692: PyObject_GC_Del (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840D2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DACB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DADB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427DACB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43156CA: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43396AE: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE242: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x6c48010 is 808 bytes inside a block of size 1,024 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x429E5EF: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x429723E: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A49: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43396AE: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5f61010 is not stack'd, malloc'd or (recently) free'd
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x428410B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x6311010 is 96 bytes inside a block of size 1,777 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42840F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988AB: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427B7E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C3297: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x429885B: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==  Address 0x5e5d010 is not stack'd, malloc'd or (recently) free'd
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Use of uninitialised value of size 4
==9324==    at 0x42B181D: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427ECC2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x636e010 is not stack'd, malloc'd or (recently) free'd
==9324== 
==9324== Conditional jump or move depends on uninitialised value(s)
==9324==    at 0x42B1812: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x427ECC2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AB8F3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315AE4: _PyImport_Fini (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320648: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5cfa010 is 184 bytes inside a block of size 665 free'd
==9324==    at 0x4022B8A: free (vg_replace_malloc.c:323)
==9324==    by 0x42B1832: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B94E6: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42988C3: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42A9850: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ABC41: PyDict_SetItem (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42AE2FE: _PyModule_Clear (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4315942: PyImport_Cleanup (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4320643: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324== 
==9324== Invalid read of size 4
==9324==    at 0x42B1809: PyObject_Free (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x426C771: PyGrammar_RemoveAccelerators (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43206CA: Py_Finalize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x804C021: iblocks::PythonPlugin::~PythonPlugin() (PythonPlugin.cc:298)
==9324==    by 0x804BF6B: main (PythonPluginTest.cc:29)
==9324==  Address 0x5d56010 is not stack'd, malloc'd or (recently) free'd
==9324== 
==9324== 
==9324== 484 bytes in 1 blocks are possibly lost in loss record 11 of 31
==9324==    at 0x4023E8C: realloc (vg_replace_malloc.c:429)
==9324==    by 0x42B1DE3: PyObject_Realloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x432D718: _PyObject_GC_Resize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4297B93: PyFrame_New (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43009D6: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300A25: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324== 
==9324== 
==9324== 66,605 bytes in 90 blocks are possibly lost in loss record 28 of 31
==9324==    at 0x4023D6E: malloc (vg_replace_malloc.c:207)
==9324==    by 0x42B1A9F: PyObject_Malloc (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42B98E7: PyString_FromStringAndSize (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42C11C2: (within /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x42ADBBC: PyCFunction_Call (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300544: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4300890: PyEval_EvalFrameEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4301EDC: PyEval_EvalCodeEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x43020F2: PyEval_EvalCode (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x431492C: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.5.so.1.0)
==9324==    by 0x4314BEB: (within /usr/lib/libpython2.5.so.1.0)
